name: big-data-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pyspark
  - numpy
  - pandas
  - jupyterlab
  - pip
  - pip:
      - kafka-python
      - confluent-kafka
      - hdfs[avro,dataframe,kerberos]